### ISSUE TITLE
有个关于协议的问题

### ISSUE THREAD

**Issue by yuzhongqi** [flyOfYW/YWPushFactoryDemo#1]
id<PushProtocol> JPushF = [[c_ss alloc] initWithLaunchOptions:launchOptions];
您好我对上面这行代码不是很理解 通过生成一个继承PushProtocol协议的JPushFactory 然后就能直接去 调用initWithLaunchOptions：协议 这个是什么原理

**Comment by flyOfYW** [comment]
这个其实只是初始化相应的推送平台的sdk，通过协议来执行，只是避免引入sdk相应的头文件，对维护起来也比较方便，假设后期换其他平台的推送，也不需要去删除相应的代码，只需继承和遵守根协议，实现相应的方法，即可

**Comment by yuzhongqi** [comment]
我尝试模仿这种协议写法，但是报错reason: '+[testProtocol testLog]: unrecognized selector sent to class 0x10c7580f8'没有找到这个类中的testLog方法
![2017-08-03 10 53 47](https://user-images.githubusercontent.com/15830038/28904017-ae3413be-783a-11e7-8e14-86dbc9cc34d7.png)
![2017-08-03 10 53 59](https://user-images.githubusercontent.com/15830038/28904019-ae84078e-783a-11e7-8552-630a597b7efe.png)
![2017-08-03 10 54 52](https://user-images.githubusercontent.com/15830038/28904020-ae8d3426-783a-11e7-8208-63f3f258b2cc.png)
![2017-08-03 10 55 17](https://user-images.githubusercontent.com/15830038/28904018-ae77ce24-783a-11e7-8a41-391c80fecf52.png)

**Comment by flyOfYW** [comment]
可以加我qq，详细跟你解释

**Comment by yuzhongqi** [comment]
你的QQ是多少

**Comment by flyOfYW** [comment]
1498627884
